CREATE TABLE "MI182_IMBUADA"."BUILDINGS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"BLDG_NAME" VARCHAR2(50), 
	"BLDG_ADD" VARCHAR2(50), 
	"BLG_ZIP" VARCHAR2(50), 
	"CUST_FNAME" VARCHAR2(50), 
	"CUST_LNAME" VARCHAR2(50), 
	 CONSTRAINT "BLDG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("ID")
	  REFERENCES "MI182_IMBUADA"."CUSTOMERS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE TABLE "MI182_IMBUADA"."CUSTOMERS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CUST_FNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"CUST_MI" VARCHAR2(50), 
	"CUST_LNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"CUST_CONT" VARCHAR2(50), 
	"CUST_ADD" VARCHAR2(50), 
	"CUST_EADD" VARCHAR2(50), 
	"CUST_JOB" VARCHAR2(50), 
	 CONSTRAINT "CUST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;